### ISSUE TITLE
studio 3.2.1编译失败

### ISSUE THREAD

**Issue by tianshaokai** [howshea/GeekNews#3]
Failed to transform file 'android.jar' to match attributes {artifactType=android-mockable-jar, returnDefaultValues=false} using transform MockableJarTransform

**Comment by howshea** [comment]
我也是3.2.1，没有这个问题，你最好检查一下你的网络，代理是不是全局可用

**Comment by tianshaokai** [comment]
gradle 插件bug，如果用27编译版本 mac studio3.2.1 我的电脑就老是编译失败，改成28就ok，或者降低gradle 插件版本

**Comment by tianshaokai** [comment]
改成28编译版本，依然编译失败
Smart cast to 'LinearLayoutManager' is impossible, because 'ry.layoutManager' is a mutable property that could have been changed by this time
